# Generated by Django 2.2.4 on 2020-05-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200424_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
